#!/usr/bin/env python3
"""Generate the parity fixture that pins the TypeScript port to this package.

The website runs a TypeScript port of `dinoclub.quiz.scoring` (see
web/src/app/quiz/engine.ts). Two implementations of the same arithmetic will
drift unless something forces them to agree, so:

  * this script scores a fixed set of answer sets with the Python reference
    and writes the results to web/src/app/quiz/parity.fixture.json
  * tests/quiz/test_parity_fixture.py fails if the committed fixture no
    longer matches what Python produces (data or algorithm changed here)
  * web/src/app/quiz/engine.spec.ts fails if the port disagrees with the
    fixture (port changed, or was not updated for a change here)

Both green means both sides agree on every number, to six decimal places.
Re-run this after editing the mini dataset or scoring.py.
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path
from typing import Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from dinoclub.quiz import DinoQuiz  # noqa: E402

FIXTURE = REPO_ROOT / "web" / "src" / "app" / "quiz" / "parity.fixture.json"
DATASET = "full"
SEED = 2024
N_RANDOM = 40


def answer_sets(quiz: DinoQuiz) -> List[Tuple[str, List[Tuple[str, str]]]]:
    """Corners, a few partial sets, then random full sets."""
    bank = list(quiz.bank)
    out = [
        ("all-first", [(q.id, q.options[0].id) for q in bank]),
        ("all-last", [(q.id, q.options[-1].id) for q in bank]),
        ("none", []),
        ("one-answer", [(bank[0].id, bank[0].options[1].id)]),
        ("half", [(q.id, q.options[i % len(q.options)].id) for i, q in enumerate(bank[: len(bank) // 2])]),
    ]
    rng = random.Random(SEED)
    for i in range(N_RANDOM):
        out.append(("random-{:02d}".format(i), [(q.id, rng.choice(q.options).id) for q in bank]))
    return out


def build(quiz: DinoQuiz) -> Dict:
    cases = []
    for label, answers in answer_sets(quiz):
        result = quiz.score(answers)
        cases.append(
            {
                "label": label,
                "answers": [list(a) for a in answers],
                "expected": {
                    "rawTotals": {k: round(v, 6) for k, v in result.raw_totals.items()},
                    "profile": {k: round(v, 6) for k, v in result.profile.items()},
                    "leaderboard": [
                        {
                            "id": m.dinosaur.id,
                            "distance": round(m.distance, 6),
                            "matchPercent": round(m.match_percent, 6),
                            "confidence": round(m.confidence, 6),
                        }
                        for m in result.matches
                    ],
                    "summary": result.summary(),
                },
            }
        )
    return {
        "note": "Generated by scripts/quiz_parity_fixture.py. Do not hand-edit; re-run the script.",
        "dataset": DATASET,
        "seed": SEED,
        "cases": cases,
    }


def main() -> int:
    quiz = DinoQuiz.load(dataset=DATASET)
    payload = build(quiz)
    FIXTURE.write_text(json.dumps(payload, indent=2) + "\n")
    print("wrote {} cases to {}".format(len(payload["cases"]), FIXTURE.relative_to(REPO_ROOT)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
